# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/PTI-LIST-WIDGET/ui/list.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 600)
        self.btn_ = QtWidgets.QPushButton(parent=Form)
        self.btn_.setGeometry(QtCore.QRect(620, 10, 93, 29))
        self.btn_.setObjectName("btn_")
        self.listWidget = QtWidgets.QListWidget(parent=Form)
        self.listWidget.setGeometry(QtCore.QRect(0, 50, 801, 641))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_.setText(_translate("Form", "PushButton"))
