# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/b1/bt/b1/bt.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 1000)
        self.lineEdit = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit.setGeometry(QtCore.QRect(240, 70, 551, 111))
        self.lineEdit.setStyleSheet("font: 700 36pt \"Segoe UI\";")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(240, 220, 551, 111))
        self.lineEdit_2.setStyleSheet("font: 700 36pt \"Segoe UI\";")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(240, 480, 551, 111))
        self.lineEdit_4.setStyleSheet("font: 700 36pt \"Segoe UI\";")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(240, 620, 551, 111))
        self.lineEdit_5.setStyleSheet("font: 700 30pt \"Segoe UI\"")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(340, 360, 371, 81))
        self.pushButton.setStyleSheet("font: 700 26pt \"Segoe UI\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 760, 371, 81))
        self.pushButton_2.setStyleSheet("font: 700 26pt \"Segoe UI\";")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lineEdit.setText(_translate("Form", "Chiều cao(cm)"))
        self.lineEdit_2.setText(_translate("Form", "Cân nặng(kg)"))
        self.lineEdit_4.setText(_translate("Form", "Kết quả BMI"))
        self.lineEdit_5.setText(_translate("Form", "Phân loại sức khỏe"))
        self.pushButton.setText(_translate("Form", "Tính BMI"))
        self.pushButton_2.setText(_translate("Form", "Xóa tất cả"))
