# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/form.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 720)
        Form.setStyleSheet("QWidget {\n"
"    background-color: rgb(255, 246, 194)}")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=Form)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 100, 1081, 611))
        self.stackedWidget.setObjectName("stackedWidget")
        self.account = QtWidgets.QWidget()
        self.account.setObjectName("account")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.account)
        self.lineEdit_3.setGeometry(QtCore.QRect(510, 80, 211, 201))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 30px")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.account)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 20, 1021, 581))
        self.lineEdit_2.setStyleSheet("background-color:rgb(255, 212, 139);\n"
"border-radius: 30px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.account)
        self.lineEdit.setGeometry(QtCore.QRect(190, 40, 721, 531))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 240, 187);\n"
"border-radius: 30px")
        self.lineEdit.setObjectName("lineEdit")
        self.txt_gender = QtWidgets.QComboBox(parent=self.account)
        self.txt_gender.setGeometry(QtCore.QRect(400, 380, 101, 41))
        self.txt_gender.setStyleSheet("background-color: rgb(255, 240, 187);\n"
"font-size: 20px")
        self.txt_gender.setObjectName("txt_gender")
        self.txt_gender.addItem("")
        self.txt_gender.addItem("")
        self.txt_gender.addItem("")
        self.txt_gender.addItem("")
        self.txt_name = QtWidgets.QLineEdit(parent=self.account)
        self.txt_name.setGeometry(QtCore.QRect(260, 120, 231, 41))
        self.txt_name.setText("")
        self.txt_name.setObjectName("txt_name")
        self.txt_email = QtWidgets.QLineEdit(parent=self.account)
        self.txt_email.setGeometry(QtCore.QRect(260, 220, 231, 41))
        self.txt_email.setObjectName("txt_email")
        self.btn_avatar = QtWidgets.QPushButton(parent=self.account)
        self.btn_avatar.setGeometry(QtCore.QRect(570, 150, 271, 261))
        self.btn_avatar.setText("")
        self.btn_avatar.setObjectName("btn_avatar")
        self.txt_birthday = QtWidgets.QDateEdit(parent=self.account)
        self.txt_birthday.setGeometry(QtCore.QRect(260, 320, 251, 41))
        self.txt_birthday.setObjectName("txt_birthday")
        self.label = QtWidgets.QLabel(parent=self.account)
        self.label.setGeometry(QtCore.QRect(260, 100, 58, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.account)
        self.label_2.setGeometry(QtCore.QRect(260, 200, 58, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.account)
        self.label_3.setGeometry(QtCore.QRect(260, 300, 58, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.account)
        self.label_4.setGeometry(QtCore.QRect(270, 390, 58, 16))
        self.label_4.setObjectName("label_4")
        self.btn_save_account = QtWidgets.QPushButton(parent=self.account)
        self.btn_save_account.setGeometry(QtCore.QRect(310, 440, 131, 51))
        self.btn_save_account.setObjectName("btn_save_account")
        self.stackedWidget.addWidget(self.account)
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.home)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 10, 1061, 591))
        self.pushButton_3.setStyleSheet("    background: qlineargradient(\n"
"        x1: 0, y1: 0,\n"
"        x2: 0, y2: 1,\n"
"        stop: 0 #ffffff,         /* top: white */\n"
"        stop: 1 #f5f5f5          /* bottom: very light grey */\n"
"    );\n"
"    border-radius: 20px;\n"
"    border: 1px solid #e0e0e0;  /* optional subtle border */\n"
"")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.frame_2 = QtWidgets.QFrame(parent=self.home)
        self.frame_2.setGeometry(QtCore.QRect(40, 30, 201, 231))
        self.frame_2.setStyleSheet("    background: rgb(255, 246, 194)\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(-20, 0, 231, 151))
        self.label_6.setStyleSheet("")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../../../../../Downloads/kake_udone-removebg-preview.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(60, 140, 91, 20))
        self.label_7.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"background-color: none")
        self.label_7.setObjectName("label_7")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(50, 190, 93, 29))
        self.pushButton_5.setStyleSheet("background-color: #FFC107;  /* Bright yellow */\n"
"    color: #000000;             /* Black text */\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 8px;         /* Rounded corners */\n"
"    padding: 5px 0;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 160, 93, 29))
        self.pushButton_4.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../../../../../Downloads/star-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(70, 160, 93, 29))
        self.pushButton_6.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_6.setText("")
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 160, 93, 29))
        self.pushButton_7.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_7.setText("")
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setObjectName("pushButton_7")
        self.frame_3 = QtWidgets.QFrame(parent=self.home)
        self.frame_3.setGeometry(QtCore.QRect(310, 30, 201, 231))
        self.frame_3.setStyleSheet("    background: rgb(255, 246, 194)\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_9 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_9.setGeometry(QtCore.QRect(40, 140, 121, 20))
        self.label_9.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"background-color: none")
        self.label_9.setObjectName("label_9")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_8.setGeometry(QtCore.QRect(50, 190, 93, 29))
        self.pushButton_8.setStyleSheet("background-color: #FFC107;  /* Bright yellow */\n"
"    color: #000000;             /* Black text */\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 8px;         /* Rounded corners */\n"
"    padding: 5px 0;")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_9.setGeometry(QtCore.QRect(50, 160, 93, 29))
        self.pushButton_9.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_9.setText("")
        self.pushButton_9.setIcon(icon)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_10.setGeometry(QtCore.QRect(70, 160, 93, 29))
        self.pushButton_10.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_10.setText("")
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_11.setGeometry(QtCore.QRect(30, 160, 93, 29))
        self.pushButton_11.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_11.setText("")
        self.pushButton_11.setIcon(icon)
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_8.setEnabled(True)
        self.label_8.setGeometry(QtCore.QRect(30, -20, 141, 191))
        self.label_8.setStyleSheet("background-color: none")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../../../../../Downloads/Curry-Udon-2-IV-removebg-preview.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.frame_4 = QtWidgets.QFrame(parent=self.home)
        self.frame_4.setGeometry(QtCore.QRect(570, 30, 201, 231))
        self.frame_4.setStyleSheet("    background: rgb(255, 246, 194)\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(-20, -10, 241, 161))
        self.label_10.setStyleSheet("")
        self.label_10.setText("")
        self.label_10.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../../../../../Downloads/istockphoto-1028123408-612x612-removebg-preview.png"))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(70, 140, 91, 20))
        self.label_11.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"background-color: none")
        self.label_11.setObjectName("label_11")
        self.btn_detail = QtWidgets.QPushButton(parent=self.frame_4)
        self.btn_detail.setGeometry(QtCore.QRect(50, 190, 93, 29))
        self.btn_detail.setStyleSheet("background-color: #FFC107;  /* Bright yellow */\n"
"    color: #000000;             /* Black text */\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 8px;         /* Rounded corners */\n"
"    padding: 5px 0;")
        self.btn_detail.setObjectName("btn_detail")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_13.setGeometry(QtCore.QRect(50, 160, 93, 29))
        self.pushButton_13.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_13.setText("")
        self.pushButton_13.setIcon(icon)
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_14.setGeometry(QtCore.QRect(70, 160, 93, 29))
        self.pushButton_14.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_14.setText("")
        self.pushButton_14.setIcon(icon)
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.frame_4)
        self.pushButton_15.setGeometry(QtCore.QRect(30, 160, 93, 29))
        self.pushButton_15.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_15.setText("")
        self.pushButton_15.setIcon(icon)
        self.pushButton_15.setObjectName("pushButton_15")
        self.frame_5 = QtWidgets.QFrame(parent=self.home)
        self.frame_5.setGeometry(QtCore.QRect(840, 30, 201, 231))
        self.frame_5.setStyleSheet("    background: rgb(255, 246, 194)\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_12 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_12.setGeometry(QtCore.QRect(10, -10, 181, 161))
        self.label_12.setStyleSheet("")
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../../../../../Downloads/rotated_takoyaki_horizontal-removebg-preview.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_13.setGeometry(QtCore.QRect(70, 140, 91, 20))
        self.label_13.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"background-color: none")
        self.label_13.setObjectName("label_13")
        self.pushButton_16 = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButton_16.setGeometry(QtCore.QRect(50, 190, 93, 29))
        self.pushButton_16.setStyleSheet("background-color: #FFC107;  /* Bright yellow */\n"
"    color: #000000;             /* Black text */\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 8px;         /* Rounded corners */\n"
"    padding: 5px 0;")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButton_17.setGeometry(QtCore.QRect(40, 160, 93, 29))
        self.pushButton_17.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_17.setText("")
        self.pushButton_17.setIcon(icon)
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(parent=self.frame_5)
        self.pushButton_18.setGeometry(QtCore.QRect(60, 160, 93, 29))
        self.pushButton_18.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_18.setText("")
        self.pushButton_18.setIcon(icon)
        self.pushButton_18.setObjectName("pushButton_18")
        self.frame_6 = QtWidgets.QFrame(parent=self.home)
        self.frame_6.setGeometry(QtCore.QRect(40, 340, 201, 231))
        self.frame_6.setStyleSheet("    background: rgb(255, 246, 194)\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_14.setGeometry(QtCore.QRect(0, 0, 201, 151))
        self.label_14.setStyleSheet("")
        self.label_14.setText("")
        self.label_14.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../../../../../Downloads/images-removebg-preview (1).png"))
        self.label_14.setScaledContents(True)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_15.setGeometry(QtCore.QRect(60, 140, 91, 20))
        self.label_15.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"background-color: none")
        self.label_15.setObjectName("label_15")
        self.pushButton_20 = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButton_20.setGeometry(QtCore.QRect(50, 190, 93, 29))
        self.pushButton_20.setStyleSheet("background-color: #FFC107;  /* Bright yellow */\n"
"    color: #000000;             /* Black text */\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 8px;         /* Rounded corners */\n"
"    padding: 5px 0;")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButton_21.setGeometry(QtCore.QRect(70, 160, 93, 29))
        self.pushButton_21.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_21.setText("")
        self.pushButton_21.setIcon(icon)
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_23 = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButton_23.setGeometry(QtCore.QRect(30, 160, 93, 29))
        self.pushButton_23.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_23.setText("")
        self.pushButton_23.setIcon(icon)
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(parent=self.frame_6)
        self.pushButton_24.setGeometry(QtCore.QRect(50, 160, 93, 29))
        self.pushButton_24.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_24.setText("")
        self.pushButton_24.setIcon(icon)
        self.pushButton_24.setObjectName("pushButton_24")
        self.frame_7 = QtWidgets.QFrame(parent=self.home)
        self.frame_7.setGeometry(QtCore.QRect(310, 340, 201, 231))
        self.frame_7.setStyleSheet("    background: rgb(255, 246, 194)\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_17 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_17.setGeometry(QtCore.QRect(30, 140, 151, 20))
        self.label_17.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"background-color: none")
        self.label_17.setObjectName("label_17")
        self.pushButton_19 = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushButton_19.setGeometry(QtCore.QRect(50, 190, 93, 29))
        self.pushButton_19.setStyleSheet("background-color: #FFC107;  /* Bright yellow */\n"
"    color: #000000;             /* Black text */\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 8px;         /* Rounded corners */\n"
"    padding: 5px 0;")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_22 = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushButton_22.setGeometry(QtCore.QRect(40, 160, 93, 29))
        self.pushButton_22.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_22.setText("")
        self.pushButton_22.setIcon(icon)
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_25 = QtWidgets.QPushButton(parent=self.frame_7)
        self.pushButton_25.setGeometry(QtCore.QRect(60, 160, 93, 29))
        self.pushButton_25.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_25.setText("")
        self.pushButton_25.setIcon(icon)
        self.pushButton_25.setObjectName("pushButton_25")
        self.label_16 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_16.setGeometry(QtCore.QRect(30, 0, 151, 131))
        self.label_16.setText("")
        self.label_16.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../../../../../Downloads/Chocolate-Molten-Lava-Cakes-27-1024x1024-removebg-preview.png"))
        self.label_16.setScaledContents(True)
        self.label_16.setObjectName("label_16")
        self.pushButton_26 = QtWidgets.QPushButton(parent=self.home)
        self.pushButton_26.setGeometry(QtCore.QRect(960, 290, 93, 29))
        self.pushButton_26.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_26.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../img/arrow-right-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_26.setIcon(icon1)
        self.pushButton_26.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_26.setObjectName("pushButton_26")
        self.frame_8 = QtWidgets.QFrame(parent=self.home)
        self.frame_8.setGeometry(QtCore.QRect(570, 340, 201, 231))
        self.frame_8.setStyleSheet("    background: rgb(255, 246, 194)\n"
"")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_18 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_18.setGeometry(QtCore.QRect(30, 140, 151, 20))
        self.label_18.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"background-color: none")
        self.label_18.setObjectName("label_18")
        self.pushButton_27 = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_27.setGeometry(QtCore.QRect(50, 190, 93, 29))
        self.pushButton_27.setStyleSheet("background-color: #FFC107;  /* Bright yellow */\n"
"    color: #000000;             /* Black text */\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 8px;         /* Rounded corners */\n"
"    padding: 5px 0;")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_28.setGeometry(QtCore.QRect(40, 160, 93, 29))
        self.pushButton_28.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_28.setText("")
        self.pushButton_28.setIcon(icon)
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_29.setGeometry(QtCore.QRect(60, 160, 93, 29))
        self.pushButton_29.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_29.setText("")
        self.pushButton_29.setIcon(icon)
        self.pushButton_29.setObjectName("pushButton_29")
        self.label_19 = QtWidgets.QLabel(parent=self.frame_8)
        self.label_19.setGeometry(QtCore.QRect(10, 0, 171, 141))
        self.label_19.setText("")
        self.label_19.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../../../../../Downloads/cheesecakeeeyy-removebg-preview.png"))
        self.label_19.setScaledContents(True)
        self.label_19.setObjectName("label_19")
        self.frame_9 = QtWidgets.QFrame(parent=self.home)
        self.frame_9.setGeometry(QtCore.QRect(840, 340, 201, 231))
        self.frame_9.setStyleSheet("    background: rgb(255, 246, 194)\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_20 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_20.setGeometry(QtCore.QRect(0, 10, 191, 131))
        self.label_20.setStyleSheet("")
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../../../../../Downloads/gyoza_dumlings.-removebg-preview.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_21.setGeometry(QtCore.QRect(40, 140, 131, 20))
        self.label_21.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"background-color: none")
        self.label_21.setObjectName("label_21")
        self.pushButton_30 = QtWidgets.QPushButton(parent=self.frame_9)
        self.pushButton_30.setGeometry(QtCore.QRect(50, 190, 93, 29))
        self.pushButton_30.setStyleSheet("background-color: #FFC107;  /* Bright yellow */\n"
"    color: #000000;             /* Black text */\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 8px;         /* Rounded corners */\n"
"    padding: 5px 0;")
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(parent=self.frame_9)
        self.pushButton_31.setGeometry(QtCore.QRect(50, 160, 93, 29))
        self.pushButton_31.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_31.setText("")
        self.pushButton_31.setIcon(icon)
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(parent=self.frame_9)
        self.pushButton_32.setGeometry(QtCore.QRect(70, 160, 93, 29))
        self.pushButton_32.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_32.setText("")
        self.pushButton_32.setIcon(icon)
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(parent=self.frame_9)
        self.pushButton_33.setGeometry(QtCore.QRect(30, 160, 93, 29))
        self.pushButton_33.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_33.setText("")
        self.pushButton_33.setIcon(icon)
        self.pushButton_33.setObjectName("pushButton_33")
        self.stackedWidget.addWidget(self.home)
        self.detail = QtWidgets.QWidget()
        self.detail.setObjectName("detail")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.detail)
        self.lineEdit_5.setGeometry(QtCore.QRect(20, 20, 1041, 581))
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 30px")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.detail)
        self.lineEdit_6.setGeometry(QtCore.QRect(20, 20, 391, 581))
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 198, 119);\n"
"border-radius: 30px")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_22 = QtWidgets.QLabel(parent=self.detail)
        self.label_22.setGeometry(QtCore.QRect(-50, 10, 541, 361))
        self.label_22.setStyleSheet("background-color: none")
        self.label_22.setText("")
        self.label_22.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../../../../../Downloads/istockphoto-1028123408-612x612-removebg-preview.png"))
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(parent=self.detail)
        self.label_23.setGeometry(QtCore.QRect(130, 350, 191, 41))
        self.label_23.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"background-color: none;\n"
"font-size: 50px")
        self.label_23.setObjectName("label_23")
        self.pushButton_34 = QtWidgets.QPushButton(parent=self.detail)
        self.pushButton_34.setGeometry(QtCore.QRect(80, 400, 93, 51))
        self.pushButton_34.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_34.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../../../../../Downloads/star-solid (white).svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_34.setIcon(icon2)
        self.pushButton_34.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(parent=self.detail)
        self.pushButton_35.setGeometry(QtCore.QRect(170, 400, 93, 51))
        self.pushButton_35.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_35.setText("")
        self.pushButton_35.setIcon(icon2)
        self.pushButton_35.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(parent=self.detail)
        self.pushButton_36.setGeometry(QtCore.QRect(260, 400, 93, 51))
        self.pushButton_36.setStyleSheet("background: none;\n"
"border: none;")
        self.pushButton_36.setText("")
        self.pushButton_36.setIcon(icon2)
        self.pushButton_36.setIconSize(QtCore.QSize(50, 50))
        self.pushButton_36.setObjectName("pushButton_36")
        self.textEdit = QtWidgets.QTextEdit(parent=self.detail)
        self.textEdit.setGeometry(QtCore.QRect(40, 450, 351, 151))
        self.textEdit.setStyleSheet("background-color: rgb(255, 198, 119);\n"
"border: 15px")
        self.textEdit.setObjectName("textEdit")
        self.label_24 = QtWidgets.QLabel(parent=self.detail)
        self.label_24.setGeometry(QtCore.QRect(430, 40, 191, 41))
        self.label_24.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"background-color: none;\n"
"font-size: 30px")
        self.label_24.setObjectName("label_24")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=self.detail)
        self.textEdit_2.setGeometry(QtCore.QRect(430, 80, 611, 75))
        self.textEdit_2.setStyleSheet("background-color: none;\n"
"border: 15px")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_25 = QtWidgets.QLabel(parent=self.detail)
        self.label_25.setGeometry(QtCore.QRect(430, 120, 191, 41))
        self.label_25.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"background-color: none;\n"
"font-size: 30px")
        self.label_25.setObjectName("label_25")
        self.textEdit_3 = QtWidgets.QTextEdit(parent=self.detail)
        self.textEdit_3.setGeometry(QtCore.QRect(430, 160, 621, 411))
        self.textEdit_3.setStyleSheet("background-color: none;\n"
"border: 15px")
        self.textEdit_3.setObjectName("textEdit_3")
        self.stackedWidget.addWidget(self.detail)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 1081, 101))
        self.frame.setStyleSheet("background-color: rgb(255, 190, 124)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.btn_home = QtWidgets.QPushButton(parent=self.frame)
        self.btn_home.setGeometry(QtCore.QRect(0, 10, 93, 81))
        self.btn_home.setStyleSheet("background: none;\n"
"border: none;\n"
"")
        self.btn_home.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../img/house-solid (3).svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_home.setIcon(icon3)
        self.btn_home.setIconSize(QtCore.QSize(50, 50))
        self.btn_home.setObjectName("btn_home")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(1000, 10, 93, 71))
        self.pushButton_2.setStyleSheet("background: none;\n"
"border: none;\n"
"")
        self.pushButton_2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../img/magnifying-glass-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_2.setIcon(icon4)
        self.pushButton_2.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(840, 30, 171, 41))
        self.lineEdit_4.setStyleSheet("border: 1px solid #e0e0e0; \n"
"    border-radius: 15px;    \n"
"    padding: 5px 15px;                \n"
"    background-color: #ffffff;        \n"
"    color: #333333;                    \n"
"    font-size: 14px; ")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.btn_profile = QtWidgets.QPushButton(parent=self.frame)
        self.btn_profile.setGeometry(QtCore.QRect(70, 20, 93, 61))
        self.btn_profile.setStyleSheet("background: none;\n"
"border: none;\n"
"")
        self.btn_profile.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../img/circle-user-solid (1).svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_profile.setIcon(icon5)
        self.btn_profile.setIconSize(QtCore.QSize(50, 50))
        self.btn_profile.setObjectName("btn_profile")

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.txt_gender.setItemText(0, _translate("Form", "Male"))
        self.txt_gender.setItemText(1, _translate("Form", "Female"))
        self.txt_gender.setItemText(2, _translate("Form", "Other"))
        self.txt_gender.setItemText(3, _translate("Form", "None"))
        self.label.setText(_translate("Form", "Name"))
        self.label_2.setText(_translate("Form", "Email"))
        self.label_3.setText(_translate("Form", "Birthday"))
        self.label_4.setText(_translate("Form", "Gender"))
        self.btn_save_account.setText(_translate("Form", "Save"))
        self.label_7.setText(_translate("Form", "Kake Udon"))
        self.pushButton_5.setText(_translate("Form", "Detail"))
        self.label_9.setText(_translate("Form", "Udon Curry Bow"))
        self.pushButton_8.setText(_translate("Form", "Detail"))
        self.label_11.setText(_translate("Form", "Phở Bò"))
        self.btn_detail.setText(_translate("Form", "Detail"))
        self.label_13.setText(_translate("Form", "Takoyaki"))
        self.pushButton_16.setText(_translate("Form", "Detail"))
        self.label_15.setText(_translate("Form", "Beefsteak"))
        self.pushButton_20.setText(_translate("Form", "Detail"))
        self.label_17.setText(_translate("Form", "Chocolate Lava Cake"))
        self.pushButton_19.setText(_translate("Form", "Detail"))
        self.label_18.setText(_translate("Form", "Japanese Cheesecake"))
        self.pushButton_27.setText(_translate("Form", "Detail"))
        self.label_21.setText(_translate("Form", "Gyoza Dumplings"))
        self.pushButton_30.setText(_translate("Form", "Detail"))
        self.label_23.setText(_translate("Form", "Phở Bò"))
        self.textEdit.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:12pt; font-weight:700;\">A traditional Vietnamese beef noodle soup with silky rice noodles, tender beef slices, and rich spiced broth — topped with fresh herbs and chili.</span></p></body></html>"))
        self.label_24.setText(_translate("Form", "Ingredients:"))
        self.textEdit_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:14pt;\">Beef balls, beef, Pho noodles and vegetable,...</span></p></body></html>"))
        self.label_25.setText(_translate("Form", "Recipe:"))
        self.textEdit_3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SFProDisplay\',\'sans-serif\'; font-size:14pt; font-weight:700; color:#181818; background-color:#ffffff; word-spacing:1.59375px;\">Step 1:</span><span style=\" font-family:\'SFProDisplay\',\'sans-serif\'; font-size:14pt; color:#181818; background-color:#ffffff; word-spacing:1.59375px;\"> Boil 500ml of water and add 20grams of noodle soup. Then, you stir them well.<br /><br /></span><span style=\" font-family:\'SFProDisplay\',\'sans-serif\'; font-size:14pt; font-weight:700; color:#181818; background-color:#ffffff; word-spacing:1.59375px;\">Step 2:</span><span style=\" font-family:\'SFProDisplay\',\'sans-serif\'; font-size:14pt; color:#181818; background-color:#ffffff; word-spacing:1.59375px;\"> Add two tablespoons of fish sauce to make the broth more flavorful.<br /></span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SFProDisplay\',\'sans-serif\'; font-size:14pt; font-weight:700; color:#181818; background-color:#ffffff; word-spacing:1.59375px;\">Step 3:</span><span style=\" font-family:\'SFProDisplay\',\'sans-serif\'; font-size:14pt; color:#181818; background-color:#ffffff; word-spacing:1.59375px;\"> Peel the raw beef or dip it longer if you want to enjoy well-cooked and soft meat.<br /><br /></span><span style=\" font-family:\'SFProDisplay\',\'sans-serif\'; font-size:14pt; font-weight:700; color:#181818; background-color:#ffffff; word-spacing:1.59375px;\">Step 4:</span><span style=\" font-family:\'SFProDisplay\',\'sans-serif\'; font-size:14pt; color:#181818; background-color:#ffffff; word-spacing:1.59375px;\"> Dip all of the beef balls in boiling water to cook. Then, you should dip the rice noodles.<br /><br /></span><span style=\" font-family:\'SFProDisplay\',\'sans-serif\'; font-size:14pt; font-weight:700; color:#181818; background-color:#ffffff; word-spacing:1.59375px;\">Step 5:</span><span style=\" font-family:\'SFProDisplay\',\'sans-serif\'; font-size:14pt; color:#181818; background-color:#ffffff; word-spacing:1.59375px;\"> Put beef balls, beef, Pho noodles, and vegetables into the broth pot. After that, move them in a bowl and relish. You could select several vegetables to improve the deliciousness of Pho such as cinnamon and herbs.<br /><br /></span><span style=\" font-family:\'SFProDisplay\',\'sans-serif\'; font-size:12pt; font-style:italic; color:#181818; background-color:#ffffff; word-spacing:1.59375px;\">- </span><span style=\" font-family:\'Segoe UI\'; font-size:12pt; font-style:italic;\">While this is a simple way to make Phở Bò, feel free to explore other variations or add your favorite toppings to make it your own -</span></p></body></html>"))
        self.lineEdit_4.setPlaceholderText(_translate("Form", "Search anything here"))
