# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/item.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(402, 462)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(0, 0, 431, 491))
        self.frame.setStyleSheet("background: rgb(255, 246, 194)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_detail = QtWidgets.QPushButton(parent=self.frame)
        self.pushButton_detail.setGeometry(QtCore.QRect(50, 390, 301, 51))
        self.pushButton_detail.setStyleSheet("background-color: #FFC107;  /* Bright yellow */\n"
"    color: #000000;             /* Black text */\n"
"    font-size: 20px;\n"
"    border: none;\n"
"    border-radius: 8px;         /* Rounded corners */\n"
"    padding: 5px 0;")
        self.pushButton_detail.setObjectName("pushButton_detail")
        self.label_rating = QtWidgets.QLabel(parent=self.frame)
        self.label_rating.setGeometry(QtCore.QRect(130, 340, 151, 51))
        self.label_rating.setStyleSheet("font-size: 30px;\n"
"background-color: none")
        self.label_rating.setObjectName("label_rating")
        self.label_picture = QtWidgets.QLabel(parent=self.frame)
        self.label_picture.setGeometry(QtCore.QRect(30, 0, 311, 311))
        self.label_picture.setText("")
        self.label_picture.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../../../../../Downloads/Curry-Udon-Featured-removebg-preview.png"))
        self.label_picture.setScaledContents(True)
        self.label_picture.setObjectName("label_picture")
        self.label_Name = QtWidgets.QLabel(parent=self.frame)
        self.label_Name.setGeometry(QtCore.QRect(120, 300, 181, 51))
        self.label_Name.setStyleSheet("font: 700 9pt \"Segoe UI\";\n"
"background-color: none ;\n"
"font-size: 30px")
        self.label_Name.setObjectName("label_Name")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_detail.setText(_translate("Form", "More detail"))
        self.label_rating.setText(_translate("Form", "⭐⭐⭐"))
        self.label_Name.setText(_translate("Form", "Kake Udon"))
