# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/login.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 720)
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(-670, 0, 1751, 731))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../../../../Pictures/20220223-SurabiDurenBangKumis.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(618, 152, 551, 61))
        self.label.setStyleSheet("font-family: \'Arial Black\', \'Impact\', sans-serif;\n"
"    font-size: 40px;\n"
"    font-weight: bold;\n"
"    color: #4B2E1E; \n"
"    letter-spacing: 0.5px;")
        self.label.setObjectName("label")
        self.btn_login = QtWidgets.QPushButton(parent=Form)
        self.btn_login.setGeometry(QtCore.QRect(580, 480, 351, 41))
        self.btn_login.setStyleSheet("background-color: #FFC107;  /* Bright yellow */\n"
"    color: #000000;             /* Black text */\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 8px;         /* Rounded corners */\n"
"    padding: 10px 0;")
        self.btn_login.setObjectName("btn_login")
        self.pushButton_5 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_5.setGeometry(QtCore.QRect(508, 122, 491, 491))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 250, 199);\n"
"    border-radius: 15px;\n"
"    padding: 15px;")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(578, 252, 111, 20))
        self.label_2.setStyleSheet("font: 9pt \"Lucida Sans Unicode\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(578, 352, 81, 20))
        self.label_3.setStyleSheet("font: 9pt \"Lucida Sans Unicode\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(648, 212, 241, 20))
        self.label_4.setStyleSheet("font: 9pt \"Lucida Sans Unicode\";")
        self.label_4.setObjectName("label_4")
        self.txt_email = QtWidgets.QLineEdit(parent=Form)
        self.txt_email.setGeometry(QtCore.QRect(578, 282, 351, 41))
        self.txt_email.setStyleSheet("border: 1px solid #e0e0e0; \n"
"    border-radius: 10px;    \n"
"    padding: 8px 12px;                \n"
"    background-color: #ffffff;        \n"
"    color: #333333;                    \n"
"    font-size: 14px; ")
        self.txt_email.setObjectName("txt_email")
        self.txt_password = QtWidgets.QLineEdit(parent=Form)
        self.txt_password.setGeometry(QtCore.QRect(578, 382, 351, 41))
        self.txt_password.setStyleSheet("border: 1px solid #e0e0e0; \n"
"    border-radius: 10px;    \n"
"    padding: 8px 12px;                \n"
"    background-color: #ffffff;        \n"
"    color: #333333;                    \n"
"    font-size: 14px; ")
        self.txt_password.setObjectName("txt_password")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(580, 450, 141, 20))
        self.label_6.setStyleSheet("font: 9pt \"Lucida Sans Unicode\";")
        self.label_6.setObjectName("label_6")
        self.btn_register = QtWidgets.QPushButton(parent=Form)
        self.btn_register.setGeometry(QtCore.QRect(830, 530, 101, 31))
        self.btn_register.setStyleSheet("background-color: #FFC107;  /* Bright yellow */\n"
"    color: #000000;             /* Black text */\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 5px;         /* Rounded corners */\n"
"    padding: 7px 0;")
        self.btn_register.setObjectName("btn_register")
        self.btn_eye = QtWidgets.QPushButton(parent=Form)
        self.btn_eye.setGeometry(QtCore.QRect(850, 390, 81, 31))
        self.btn_eye.setStyleSheet("background: none;\n"
"border: none;\n"
"")
        self.btn_eye.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../img/eye-slash-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eye.setIcon(icon)
        self.btn_eye.setObjectName("btn_eye")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(580, 540, 201, 20))
        self.label_5.setStyleSheet("font: 9pt \"Lucida Sans Unicode\";")
        self.label_5.setObjectName("label_5")
        self.label_7.raise_()
        self.pushButton_5.raise_()
        self.label.raise_()
        self.btn_login.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.txt_email.raise_()
        self.txt_password.raise_()
        self.label_6.raise_()
        self.btn_register.raise_()
        self.btn_eye.raise_()
        self.label_5.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Welcome Back!"))
        self.btn_login.setText(_translate("Form", "Login"))
        self.label_2.setText(_translate("Form", "Email andress"))
        self.label_3.setText(_translate("Form", "Password"))
        self.label_4.setText(_translate("Form", "Please login to your account"))
        self.txt_email.setPlaceholderText(_translate("Form", "Input your email here"))
        self.txt_password.setPlaceholderText(_translate("Form", "Input your password here"))
        self.label_6.setText(_translate("Form", "Forgot password?"))
        self.btn_register.setText(_translate("Form", "Register"))
        self.label_5.setText(_translate("Form", "Don\'t have an account yet?"))
