# Form implementation generated from reading ui file '/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/register.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1080, 720)
        self.label_7 = QtWidgets.QLabel(parent=Form)
        self.label_7.setGeometry(QtCore.QRect(-660, -10, 1751, 731))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../../../../Pictures/20220223-SurabiDurenBangKumis.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(510, 60, 551, 61))
        self.label.setStyleSheet("font-family: \'Arial Black\', \'Impact\', sans-serif;\n"
"    font-size: 27px;\n"
"    font-weight: bold;\n"
"    color: #4B2E1E; \n"
"    letter-spacing: 0.5px;")
        self.label.setObjectName("label")
        self.btn_register = QtWidgets.QPushButton(parent=Form)
        self.btn_register.setGeometry(QtCore.QRect(570, 560, 351, 41))
        self.btn_register.setStyleSheet("background-color: #FFC107;  /* Bright yellow */\n"
"    color: #000000;             /* Black text */\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 8px;         /* Rounded corners */\n"
"    padding: 10px 0;")
        self.btn_register.setObjectName("btn_register")
        self.pushButton_5 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_5.setGeometry(QtCore.QRect(500, 50, 491, 601))
        self.pushButton_5.setStyleSheet("background-color: rgb(255, 250, 199);\n"
"    border-radius: 15px;\n"
"    padding: 15px;")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(570, 240, 111, 20))
        self.label_2.setStyleSheet("font: 9pt \"Lucida Sans Unicode\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(570, 340, 81, 20))
        self.label_3.setStyleSheet("font: 9pt \"Lucida Sans Unicode\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Form)
        self.label_4.setGeometry(QtCore.QRect(680, 110, 111, 20))
        self.label_4.setStyleSheet("font: 9pt \"Lucida Sans Unicode\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Form)
        self.label_5.setGeometry(QtCore.QRect(570, 440, 201, 20))
        self.label_5.setStyleSheet("font: 9pt \"Lucida Sans Unicode\";")
        self.label_5.setObjectName("label_5")
        self.txt_email = QtWidgets.QLineEdit(parent=Form)
        self.txt_email.setGeometry(QtCore.QRect(570, 270, 351, 41))
        self.txt_email.setStyleSheet("border: 1px solid #e0e0e0; \n"
"    border-radius: 10px;    \n"
"    padding: 8px 12px;                \n"
"    background-color: #ffffff;        \n"
"    color: #333333;                    \n"
"    font-size: 14px; ")
        self.txt_email.setObjectName("txt_email")
        self.txt_password = QtWidgets.QLineEdit(parent=Form)
        self.txt_password.setGeometry(QtCore.QRect(570, 370, 351, 41))
        self.txt_password.setStyleSheet("border: 1px solid #e0e0e0; \n"
"    border-radius: 10px;    \n"
"    padding: 8px 12px;                \n"
"    background-color: #ffffff;        \n"
"    color: #333333;                    \n"
"    font-size: 14px; ")
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.txt_confirm_password = QtWidgets.QLineEdit(parent=Form)
        self.txt_confirm_password.setGeometry(QtCore.QRect(570, 470, 351, 41))
        self.txt_confirm_password.setStyleSheet("border: 1px solid #e0e0e0; \n"
"    border-radius: 10px;    \n"
"    padding: 8px 12px;                \n"
"    background-color: #ffffff;        \n"
"    color: #333333;                    \n"
"    font-size: 14px; ")
        self.txt_confirm_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_confirm_password.setObjectName("txt_confirm_password")
        self.label_6 = QtWidgets.QLabel(parent=Form)
        self.label_6.setGeometry(QtCore.QRect(570, 520, 171, 20))
        self.label_6.setObjectName("label_6")
        self.btn_login = QtWidgets.QPushButton(parent=Form)
        self.btn_login.setGeometry(QtCore.QRect(810, 520, 93, 29))
        self.btn_login.setStyleSheet("background-color: #FFC107;  /* Bright yellow */\n"
"    color: #000000;             /* Black text */\n"
"    font-weight: bold;\n"
"    font-size: 14px;\n"
"    border: none;\n"
"    border-radius: 8px;         /* Rounded corners */\n"
"    padding: 5px 0;")
        self.btn_login.setObjectName("btn_login")
        self.label_8 = QtWidgets.QLabel(parent=Form)
        self.label_8.setGeometry(QtCore.QRect(570, 140, 81, 20))
        self.label_8.setStyleSheet("font: 9pt \"Lucida Sans Unicode\";")
        self.label_8.setObjectName("label_8")
        self.txt_name = QtWidgets.QLineEdit(parent=Form)
        self.txt_name.setGeometry(QtCore.QRect(570, 170, 351, 41))
        self.txt_name.setStyleSheet("border: 1px solid #e0e0e0; \n"
"    border-radius: 10px;    \n"
"    padding: 8px 12px;                \n"
"    background-color: #ffffff;        \n"
"    color: #333333;                    \n"
"    font-size: 14px; ")
        self.txt_name.setObjectName("txt_name")
        self.btn_eye_p = QtWidgets.QPushButton(parent=Form)
        self.btn_eye_p.setGeometry(QtCore.QRect(850, 370, 81, 31))
        self.btn_eye_p.setStyleSheet("background: none;\n"
"border: none;\n"
"")
        self.btn_eye_p.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("/Users/pinxun/Documents/MindX/PTA/PTA09/NgocThu/python.app/ui/../img/eye-slash-solid.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_eye_p.setIcon(icon)
        self.btn_eye_p.setObjectName("btn_eye_p")
        self.btn_eye_cp = QtWidgets.QPushButton(parent=Form)
        self.btn_eye_cp.setGeometry(QtCore.QRect(850, 470, 81, 31))
        self.btn_eye_cp.setStyleSheet("background: none;\n"
"border: none;\n"
"")
        self.btn_eye_cp.setText("")
        self.btn_eye_cp.setIcon(icon)
        self.btn_eye_cp.setObjectName("btn_eye_cp")
        self.label_7.raise_()
        self.pushButton_5.raise_()
        self.label.raise_()
        self.btn_register.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.txt_email.raise_()
        self.txt_password.raise_()
        self.txt_confirm_password.raise_()
        self.label_6.raise_()
        self.btn_login.raise_()
        self.label_8.raise_()
        self.txt_name.raise_()
        self.btn_eye_p.raise_()
        self.btn_eye_cp.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Welcome to Surabi Duren Bang Kumis"))
        self.btn_register.setText(_translate("Form", "Sign up"))
        self.label_2.setText(_translate("Form", "Email andress"))
        self.label_3.setText(_translate("Form", "Password"))
        self.label_4.setText(_translate("Form", "Please sign up"))
        self.label_5.setText(_translate("Form", "Confirmed password"))
        self.txt_email.setPlaceholderText(_translate("Form", "Input your email here"))
        self.txt_password.setPlaceholderText(_translate("Form", "Input your password here"))
        self.txt_confirm_password.setPlaceholderText(_translate("Form", "Confirm your password here"))
        self.label_6.setText(_translate("Form", "Already have an account?"))
        self.btn_login.setText(_translate("Form", "Login"))
        self.label_8.setText(_translate("Form", "Username"))
        self.txt_name.setPlaceholderText(_translate("Form", "Input your username here"))
